/* AUTOGENERATED FILE, DO NOT EDIT MANUALLY */
#include <amdregdb/AmdRegDb.h>
#include <util/util.h>
#include "dce_11_2.h"

namespace amdregdb {

static const RegBlock regBlock = {
    .name = "dce_dce_11_2",
    .regs = dce_dce_11_2_regs,
    .size = ARRAY_SIZE(dce_dce_11_2_regs)
};

void load_dce_dce_11_2() {
    static bool hasLoaded = false;
    if (hasLoaded) {
        return;
    }
    gRegDb.push_back(&regBlock);
    hasLoaded = true;
}

}; //namespace amdregdb
