/* AUTOGENERATED FILE, DO NOT EDIT MANUALLY */
#pragma once

#include <vector>
#include <util/util.h>
#include <amdregdb/RegSpec.h>

namespace amdregdb {

void load_bif_bif_3_0();
void load_bif_bif_4_1();
void load_bif_bif_5_0();
void load_bif_bif_5_1();
void load_dce_dce_10_0();
void load_dce_dce_11_0();
void load_dce_dce_11_2();
void load_dce_dce_6_0();
void load_dce_dce_8_0();
void load_gca_gfx_6_0();
void load_gca_gfx_7_2();
void load_gca_gfx_8_0();
void load_gca_gfx_8_1();
void load_gmc_gmc_6_0();
void load_gmc_gmc_7_0();
void load_gmc_gmc_7_1();
void load_gmc_gmc_8_1();
void load_gmc_gmc_8_2();
void load_oss_oss_1_0();
void load_oss_oss_2_0();
void load_oss_oss_2_4();
void load_oss_oss_3_0_1();
void load_oss_oss_3_0();
void load_smu_smu_6_0();
void load_smu_smu_7_0_0();
void load_smu_smu_7_0_1();
void load_smu_smu_7_1_0();
void load_smu_smu_7_1_1();
void load_smu_smu_7_1_2();
void load_smu_smu_7_1_3();
void load_smu_smu_8_0();
void load_uvd_uvd_4_0();
void load_uvd_uvd_4_2();
void load_uvd_uvd_5_0();
void load_uvd_uvd_6_0();
void load_vce_vce_1_0();
void load_vce_vce_2_0();
void load_vce_vce_3_0();

extern std::vector<const RegBlock*> gRegDb;

static inline void load_all_blocks() {
    load_bif_bif_3_0();
    load_bif_bif_4_1();
    load_bif_bif_5_0();
    load_bif_bif_5_1();
    load_dce_dce_10_0();
    load_dce_dce_11_0();
    load_dce_dce_11_2();
    load_dce_dce_6_0();
    load_dce_dce_8_0();
    load_gca_gfx_6_0();
    load_gca_gfx_7_2();
    load_gca_gfx_8_0();
    load_gca_gfx_8_1();
    load_gmc_gmc_6_0();
    load_gmc_gmc_7_0();
    load_gmc_gmc_7_1();
    load_gmc_gmc_8_1();
    load_gmc_gmc_8_2();
    load_oss_oss_1_0();
    load_oss_oss_2_0();
    load_oss_oss_2_4();
    load_oss_oss_3_0_1();
    load_oss_oss_3_0();
    load_smu_smu_6_0();
    load_smu_smu_7_0_0();
    load_smu_smu_7_0_1();
    load_smu_smu_7_1_0();
    load_smu_smu_7_1_1();
    load_smu_smu_7_1_2();
    load_smu_smu_7_1_3();
    load_smu_smu_8_0();
    load_uvd_uvd_4_0();
    load_uvd_uvd_4_2();
    load_uvd_uvd_5_0();
    load_uvd_uvd_6_0();
    load_vce_vce_1_0();
    load_vce_vce_2_0();
    load_vce_vce_3_0();
}

}; //namespace amdregdb
