/* AUTOGENERATED FILE, DO NOT EDIT MANUALLY */
#include <amdregdb/AmdRegDb.h>
#include <util/util.h>
#include "uvd_5_0.h"

namespace amdregdb {

static const RegBlock regBlock = {
    .name = "uvd_uvd_5_0",
    .regs = uvd_uvd_5_0_regs,
    .size = ARRAY_SIZE(uvd_uvd_5_0_regs)
};

void load_uvd_uvd_5_0() {
    static bool hasLoaded = false;
    if (hasLoaded) {
        return;
    }
    gRegDb.push_back(&regBlock);
    hasLoaded = true;
}

}; //namespace amdregdb
