/* AUTOGENERATED FILE, DO NOT EDIT MANUALLY */
#include <amdregdb/AmdRegDb.h>
#include <util/util.h>
#include "gfx_7_2.h"

namespace amdregdb {

static const RegBlock regBlock = {
    .name = "gca_gfx_7_2",
    .regs = gca_gfx_7_2_regs,
    .size = ARRAY_SIZE(gca_gfx_7_2_regs)
};

void load_gca_gfx_7_2() {
    static bool hasLoaded = false;
    if (hasLoaded) {
        return;
    }
    gRegDb.push_back(&regBlock);
    hasLoaded = true;
}

}; //namespace amdregdb
